version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
build_script:
  - gradlew.bat -u -i assemble
test_script:
  - gradlew.bat -u -i -S check
