version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - java -version
  - echo %PATH%
  - echo %GEM_PATH%
  - echo %GEM_HOME%
  - echo %JRUBY_OPTS%
build_script:
  - gradlew.bat -u -i assemble
test_script:
  - gradlew.bat -u -i -S check
